[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[variables]
APP_NAME = "MarketplaceBackend"
APP_ENV = "production"
APP_DEBUG = "true"
LOG_LEVEL = "debug"
RUN_MIGRATIONS = "true"

# Customize these for your PHP/Laravel settings
# PHP_MEMORY_LIMIT = "256M"
# PHP_MAX_EXECUTION_TIME = "60" 