[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 600
startupTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
startCommand = "./start-railway.sh"

[variables]
APP_NAME = "MarketplaceBackend"
APP_ENV = "production"
APP_DEBUG = "true"
LOG_LEVEL = "debug"
RUN_MIGRATIONS = "true"
LOG_CHANNEL = "stderr"

# Database configuration (replace with your actual config)
DB_CONNECTION = "mysql"
DB_HOST = "${MYSQLHOST}"
DB_PORT = "${MYSQLPORT}"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"

# Customize these for your PHP/Laravel settings
# PHP_MEMORY_LIMIT = "256M"
# PHP_MAX_EXECUTION_TIME = "60" 